[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ruma = "E2iAM2RNDLgMAY5jBsr2WiTqL6umZ4wkZhBBvmEBGWJ5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "ruma-wallet.json"

[scripts]
test = "bunx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
