[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.17"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ruma = "W1DWMF7dqukW5wSzEoDPsRPSyMB8oyAgcooQCn9G8UE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "ruma-wallet.json"

[scripts]
test = "bun test --timeout 1000000"
